MESSAGES:
  Start_cmd: |
    Howdy, {first_name}! ğŸ‘‹

    Now, send and schedule Tweets right from Telegram! â³ğŸ¦

    Send a message with the following syntax to see the magic. ğŸª„
    `tweet <space> <your tweet>`

    Or send `/help` for a full guide ğŸ˜‰

  Start_cmd_welcome: |
    Hi, {first_name}! ğŸ‘‹

    I guess we are already connected, you do not need to re-authorize to start sending tweets.

    Send `/help` for a list of commands. ğŸ˜‰

  Help_cmd: |
    Howdy, {first_name}! ğŸ‘‹

    With me, you can now send and schedule tweets right from Telegram! â³ğŸ¦

    Use the given syntaxes to see the magic. ğŸª„

    *Send a single tweet*
    `tweet <space> <your tweet here>`

    *Create a thread*
    `tweet <new-line> ///<first tweet> <new-line> ///<second tweet>`

  Edit_err: |
    Edited a message with a bot? ğŸ˜‚

  Unrecognized_err: |
    beep. bop. beep. ğŸ¤–

    I couldn't understand you.

    Send `/help` to know the proper syntax.

  Attachment_err: |
    Attachments aren't supported, my friend.

  App_err: |
    Seems like something's wrong. Drop me a message at @cryptic_code and I will fix it ASAP.

  Auth_missing_err: |
    Hey, {first_name}! You first need to connect me to your Twitter account!

  Auth_instructions: |
    Alright, here are the steps for authorization:

    1. Go to the URL at the bottom o this message
    2. Login to your Twitter account
    3. Authorize this bot to connect to your Twitter account.
    4. Send back the code to me `/code <your-code-here>` syntax
    5. That's it!

    {auth_url}

  Auth_sucess: |
    Yay!ğŸ¥³ Authorization was successful.

  Auth_err: |
    Authorization failed! Please, try again.

  Tweet_sucess: |
    Tweeted your tweet! âœ…

    Here's the link:
    {tweet_url}

    Like this bot? Buy me a coffee â˜• at:
    {bmc_url}
  
  Tweet_thread_success: |
    Tweeted your thread! âœ…

    Here's the link:
    {tweet_url}
  
  Tweet_err: |
    Seem's like something's wrong with the Twitter API. Drop me a message @cryptic_code and I will look into it.
  
  Tweet_lengthy: |
    Oops! Your tweet seems to have {msg_len} charcters. Trim it down to 280 characters or create a thread.

  Tweet_thread_lengthy: |
    Oops! Your {msg_index}th tweet seems to have {msg_len} charcters. Trim it down to 280 characters or create a thread.

  Tweet_valid: |
    Sharp! Your tweet(s) is/are within the 280 character limit.

  Stats_cmd: |
    Soo...

    You have sent {tweet_count} tweets with me till now.