MESSAGES:
  Start_cmd: |
    Howdy, {first_name}! ğŸ‘‹

    Now, send and schedule Tweets right from Telegram! â³ğŸ¦

    Send a message with the following syntax to see the magic. ğŸ”®
    `Tweet <enter> <enter> <your tweet>`

    Or send `/help` for a full guide ğŸ˜‰

  Start_cmd_welcome: |
    Hi, {first_name}! ğŸ‘‹

    I guess we are already connected, you might not need to re-authorize to start sending tweets.

    Send `/help` for the guide ğŸ˜‰

  Help_cmd: |
    Howdy, {first_name}\! ğŸ‘‹

    With me, you can now send and schedule tweets right from Telegram\! â³ğŸ¦

    Use the given syntaxes to see the magic\. ğŸ”®

    *Create a single tweet*
    Send a message with the following syntax:
    
    `Tweet <enter> <enter> <your tweet>`

    *Create a thread*
    Use the above syntax and follow it with `///` to indicate the beginning of the next tweet\. You may have new lines or spaces around `///` if you like for better formatting\.

    *Scheduling Tweets*
    You can use Telegram's built\-in "Schedule Send" feature to achieve that\.

    *See if your tweets are valid beforehand \(for scheduling\)*
    Same syntax as sending out a tweet/thread, just start the message with `Scan` instead of `Tweet`\.

    *See samples*
    Send `/samples` to see sample messages/tweets to send\.

    *Authorize the Bot*
    Send `/auth` to authorize/re\-authorize the bot with your Twitter account\.

    *Verify Authorization*
    Send `/verify <space> <your code>` to complete the authorization\.

    *See your stats*
    Send `/stats` to see the number of tweets you sent with this bot\.

  Stats_cmd: |
    You have sent {tweet_count} tweet(s) with me till now ğŸ‘€

  Edit_err: |
    Edited a message sent to a bot? ğŸ˜‚

  Unrecognized_err: |
    beep. bop. ğŸ¤–

    I couldn't understand you.

    Send `/help` to know the proper syntax.

  Attachment_err: |
    Attachments aren't yet supported, my friend.

  App_err: |
    Seems like something's wrong. Drop me a message at @cryptic_code and I will fix it ASAP.

  Auth_missing_err: |
    Hey, {first_name}! You first need to connect me to your Twitter account!

    Send `/auth` or `/help`

  Auth_instructions: |
    Alright, here are the steps for authorization:

    1. Go to the URL at the bottom of this message
    2. Login to your Twitter account
    3. Authorize this bot to connect to your Twitter account
    4. Send back the code you receive in a message with `/verify <your-code-here>` syntax
    5. And, that's it!

    {auth_url}

  Auth_success: |
    Yay!ğŸ¥³ Authorization was successful.

  Auth_err: |
    Authorization failed! Please, try again.

  Tweet_success: |
    Tweeted your tweet! âœ…

    Here's the link:
    {tweet_url}

    Like this bot? Buy me a coffee â˜• at:
    {bmc_url}
  
  Tweet_thread_success: |
    Tweeted your thread! âœ…

    Here's the link:
    {tweet_url}

    Like this bot? Buy me a coffee â˜• at:
    {bmc_url}
  
  Tweet_err: |
    Seem's like something's wrong with the Twitter API. Drop me a message @cryptic_code and I will look into it.
  
  Tweet_lengthy: |
    Oops! Your tweet seems to have {msg_len} charcters. Trim it down to 280 characters or create a thread.

  Tweet_thread_lengthy: |
    Oops! Your {msg_index}th tweet seems to have {msg_len} charcters. Trim it down to 280 characters or create a thread.

  Tweet_valid: |
    Sharp! Your tweet(s) is/are within the 280 character limit.

  Sample_tweet: |
    Tweet

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at hendrerit quam. Aenean dolor dui, tempus sed lectus eu, ornare elementum nulla.

  Sample_thread: |
    Tweet

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at hendrerit quam.

    ///
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at hendrerit quam.

    ///
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque at hendrerit quam.
