MESSAGES:
  START_CMD: |
    Howdy! ğŸ‘‹
    
    Now, schedule Tweets from Telegram! ğŸ¦
    
    Send a message with the following syntax to see the magic. ğŸª„
    `tweet <space> <your tweet>`

    Send `/help` for a full guide ğŸ˜‰

  HELP_CMD: |
    Howdy! ğŸ‘‹

    *This bot helps you scheule tweets right from Telegram!* ğŸ¦

    #### Send a single tweet
    `tweet <space> <your tweet here>`

    #### Create a thread
    `tweet <new-line> ///<first tweet> <new-line> ///<second tweet>`

  INVALID_ERR: |
    Your word is invalidâ— Try a different word.

  EDIT_ERR: |
    I do not care about edited messages. ğŸ˜›

  UNRECOGNIZED_ERR: |
    beep. bop. beep. ğŸ¤–

    I couldn't understand you.

    Send `/help` to know the proper syntax.
  
  ATTACHMENT_ERR: |
    Attachments aren't supported, my friend.